-- Criar a tabela de categorias
create table public.categorias (
    id bigint generated by default as identity primary key,
    nome text not null
);

-- Criar a tabela de usuarios
create table public.usuarios (
    id bigint generated by default as identity primary key,
    nome text,
    username text not null unique,
    password text not null
);

-- Criar a tabela de lancamentos
create table public.lancamentos (
    id bigint generated by default as identity primary key,
    descricao text not null,
    valor numeric not null,
    data date not null,
    categoria_id bigint references public.categorias(id)
);

-- Habilitar a Segurança em Nível de Linha (Row Level Security - RLS)
-- Esta é uma boa prática de segurança do Supabase
alter table public.categorias enable row level security;
alter table public.usuarios enable row level security;
alter table public.lancamentos enable row level security;
